// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Payment struct {
	ID        uuid.UUID    `json:"id"`
	Amount    float64      `json:"amount"`
	Currency  string       `json:"currency"`
	Reference string       `json:"reference"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
