// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (amount, currency, reference, status)
VALUES ($1, $2, $3, $4)
RETURNING id, amount::float8, currency, reference, status, created_at, updated_at
`

type CreatePaymentParams struct {
	Amount    float64 `json:"amount"`
	Currency  string  `json:"currency"`
	Reference string  `json:"reference"`
	Status    string  `json:"status"`
}

type CreatePaymentRow struct {
	ID        uuid.UUID    `json:"id"`
	Amount    float64      `json:"amount"`
	Currency  string       `json:"currency"`
	Reference string       `json:"reference"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.Status,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, amount::float8, currency, reference, status, created_at, updated_at
FROM payments
WHERE id = $1
`

type GetPaymentByIDRow struct {
	ID        uuid.UUID    `json:"id"`
	Amount    float64      `json:"amount"`
	Currency  string       `json:"currency"`
	Reference string       `json:"reference"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, amount::float8, currency, reference, status, created_at, updated_at
FROM payments
WHERE reference = $1
`

type GetPaymentByReferenceRow struct {
	ID        uuid.UUID    `json:"id"`
	Amount    float64      `json:"amount"`
	Currency  string       `json:"currency"`
	Reference string       `json:"reference"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const processPaymentIdempotent = `-- name: ProcessPaymentIdempotent :one
SELECT id, amount::float8, currency, reference, status, created_at, updated_at
FROM payments
WHERE id = $1
FOR UPDATE
`

type ProcessPaymentIdempotentRow struct {
	ID        uuid.UUID    `json:"id"`
	Amount    float64      `json:"amount"`
	Currency  string       `json:"currency"`
	Reference string       `json:"reference"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ProcessPaymentIdempotent(ctx context.Context, id uuid.UUID) (ProcessPaymentIdempotentRow, error) {
	row := q.db.QueryRowContext(ctx, processPaymentIdempotent, id)
	var i ProcessPaymentIdempotentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}
