// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error)
	GetPaymentByReference(ctx context.Context, reference string) (GetPaymentByReferenceRow, error)
	ProcessPaymentIdempotent(ctx context.Context, id uuid.UUID) (ProcessPaymentIdempotentRow, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
